[options]
admin_passwd = odoo_pass
addons_path =  /mnt/extra-addons/custom_addons/

db_host = db
db_port = 5432
db_user = odoo
db_password = odoo


redis_host = redis_15_2
redis_enabled = True

limit_request = 65536
limit_time_cpu  = 120000
limit_time_real = 120000
limit_time_real_cron = -1

;server_wide_modules = base,web

; csv_internal_sep = ,
; db_maxconn = 64
; db_name = False
; db_template = template1
;dbfilter = ^v17_soltein_0$
dbfilter = .*

debug_mode = True
; email_from = False
limit_memory_hard = 2684354560
imit_memory_soft  = 2147483648
list_db = True
; log_db = False
; log_handler = [':ERROR']
log_level = warn
logfile = /var/lib/odoo/log/odoo.log
; longpolling_port = 8072
; max_cron_threads = 1
; osv_memory_age_limit = 1.0
; osv_memory_count_limit = False
; smtp_password = False
; smtp_port = 25
; smtp_server = localhost
; smtp_ssl = False
; smtp_user = False
; workers = 6
; xmlrpc = True
; xmlrpc_interface = 
; xmlrpc_port = 8069
; xmlrpcs = True
; xmlrpcs_interface = 
; xmlrpcs_port = 8071

proxy_mode = False